# Generated by Django 5.2.4 on 2025-08-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_user_options_alter_user_managers_user_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('price', models.FloatField()),
                ('transactionId', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('orderId', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
    ]
