# Generated by Django 5.2.4 on 2025-08-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
