# Generated by Django 5.2.4 on 2025-08-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productreview',
        ),
    ]
